baseURL = "https://tsunami42.github.io/blog"
languageCode = "en-us"
title = "My Site For Everything"
theme = "minimal"

[params]
    author = "苏拉米"
    description = "随便写一下"
    githubUsername = "tsunami42"
    accent = "black"
    showBorder = true
    backgroundColor = "white"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "shell"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.icon]]
    url = "https://github.com/tsunami42/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/_Tsunami_42_/"
    name = "twitter"
    weight = 3